/**
 * phiColumnsBridge.test.ts — PHI bridge drift guard (SPEC §2.5, NL2SQL P0).
 *
 * The authoritative PHI column set lives in lib/phiScrubber.ts (`PHI_COLUMNS`).
 * `config/phi_columns.json` is a checked-in projection of that set, generated by
 * `npm run phi:sync` (scripts/gen-phi-columns.mjs), consumed by the Python prep
 * toolchain and the CI PHI gate so both languages reuse the EXACT same set.
 *
 * This test recomputes the hash directly from `PHI_COLUMNS` + `normalizeKey` and
 * asserts it equals the committed `phiColumnsetHash`. If someone edits PHI_COLUMNS
 * without re-running `phi:sync`, the bridge is stale and this fails — the drift
 * guard the whole scheme depends on.
 */
import { createHash } from 'node:crypto'
import { describe, expect, it } from 'vitest'

import phiColumnsConfig from '@/config/phi_columns.json'
import { PHI_COLUMNS, normalizeKey } from '@/lib/phiScrubber'

/** Mirror scripts/gen-phi-columns.mjs exactly: normalize, dedupe, sort. */
function normalizedSortedColumns(): string[] {
  return Array.from(
    new Set(Array.from(PHI_COLUMNS, (key) => normalizeKey(String(key))))
  ).toSorted()
}

function computeHash(columns: string[]): string {
  return createHash('sha256').update(columns.join(',')).digest('hex')
}

describe('PHI columns bridge (config/phi_columns.json ↔ phiScrubber.PHI_COLUMNS)', () => {
  it('regenerated hash matches the committed phiColumnsetHash (bridge not stale)', () => {
    const columns = normalizedSortedColumns()
    const expectedHash = computeHash(columns)
    expect(phiColumnsConfig.phiColumnsetHash).toBe(expectedHash)
  })

  it('committed phiColumns list matches the runtime PHI_COLUMNS set', () => {
    expect(phiColumnsConfig.phiColumns).toEqual(normalizedSortedColumns())
  })

  it("committed hash is self-consistent with its own phiColumns list", () => {
    // Guards against a hand-edited JSON whose list and hash disagree.
    expect(computeHash(phiColumnsConfig.phiColumns.toSorted())).toBe(
      phiColumnsConfig.phiColumnsetHash
    )
  })
})
